import { Card, CardContent } from "@/components/ui/card";
import { Play } from "lucide-react";
import { useT } from "@/i18n/LanguageContext";

type VideoItem = {
  videoId: string;
  titleEs: string;
  titleEn: string;
  descEs: string;
  descEn: string;
  uploadDate: string;
  durationISO: string;
  durationLabel: string;
  featured?: boolean;
};

const VIDEOS: VideoItem[] = [
  {
    videoId: "_DTHLj04qvs",
    titleEs: "Videoclip Oficial: Perfecta en Pixeles",
    titleEn: "Official Video: Perfect in Pixels",
    descEs: "Una critica audiovisual a la perfeccion digital. Composicion musical y produccion de video realizada 100 por ciento con herramientas de IA Generativa.",
    descEn: "An audiovisual critique of digital perfection. Music composition and video production made 100 percent with Generative AI tools.",
    uploadDate: "2025-01-23",
    durationISO: "PT2M17S",
    durationLabel: "2:17",
    featured: true,
  },
  {
    videoId: "hVl9x0joXyk",
    titleEs: "Videoarte: Sin Empleo 4.0",
    titleEn: "Video Art: Jobless 4.0",
    descEs: "Satira musical sobre la automatizacion laboral. Ritmos latinos con esteticas sinteticas generadas por IA.",
    descEn: "Musical satire about labor automation. Latin rhythms with synthetic aesthetics generated by AI.",
    uploadDate: "2025-01-29",
    durationISO: "PT3M7S",
    durationLabel: "3:07",
  },
  {
    videoId: "u4iOgbba3mQ",
    titleEs: "Conferencia MinTIC: Fusion Creativa IA y Produccion Audiovisual",
    titleEn: "MinTIC Lecture: Creative AI Fusion and Audiovisual Production",
    descEs: "Workshop practico sobre la integracion de herramientas de IA en flujos de produccion audiovisual.",
    descEn: "Hands-on workshop on integrating AI tools into audiovisual production workflows.",
    uploadDate: "2024-11-21",
    durationISO: "PT51M40S",
    durationLabel: "51:40",
  },
  {
    videoId: "xkUaEKGru00",
    titleEs: "Masterclass IEP: Innovacion Musical con IA",
    titleEn: "IEP Masterclass: Musical Innovation with AI",
    descEs: "Taller de composicion creativa con IA Generativa para musicos y productores.",
    descEn: "Creative composition workshop with Generative AI for musicians and producers.",
    uploadDate: "2025-05-22",
    durationISO: "PT1H12M48S",
    durationLabel: "1:12:48",
  },
  {
    videoId: "851BrxRWLV0",
    titleEs: "La IA es tu musa o tu verdugo: Educacion para Artistas",
    titleEn: "AI is your muse or your executioner: Education for Artists",
    descEs: "Conferencia sobre como los artistas deben adoptar la IA como herramienta de potenciacion creativa.",
    descEn: "Lecture on how artists should adopt AI as a creative empowerment tool.",
    uploadDate: "2025-06-12",
    durationISO: "PT12M13S",
    durationLabel: "12:13",
  },
  {
    videoId: "4i7BwIBIOww",
    titleEs: "AI-VOLUTION: Cortometraje Experimental 100 por ciento IA",
    titleEn: "AI-VOLUTION: 100 percent AI Experimental Short Film",
    descEs: "Cortometraje de ciencia ficcion realizado integramente con IA Generativa y Face Swap.",
    descEn: "Sci-fi short film made entirely with Generative AI and Face Swap.",
    uploadDate: "2025-05-01",
    durationISO: "PT10M00S",
    durationLabel: "10:00",
    featured: true,
  },
];

const youtubeThumb = (id: string) => `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`;
const youtubeThumbFallback = (id: string) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
const youtubeUrl = (id: string) => `https://www.youtube.com/watch?v=${id}`;
const youtubeEmbed = (id: string) => `https://www.youtube.com/embed/${id}`;

const Portfolio = () => {
  const { lang, t } = useT();
  const handleImgLoad = (e: React.SyntheticEvent<HTMLImageElement>, videoId: string) => {
    const img = e.currentTarget;
    if (img.naturalWidth < 200 && !img.src.includes("hqdefault")) {
      img.src = youtubeThumbFallback(videoId);
    }
  };
  return (
    <section id="portfolio" className="py-24 md:py-28 bg-background" itemScope itemType="https://schema.org/ItemList" aria-labelledby="portfolio-heading">
      <meta itemProp="name" content="Portafolio de Videos - Paula Pinzón" />
      <div className="container mx-auto px-4">
        <div className="text-center mb-14">
          <h2 id="portfolio-heading" className="font-display font-bold tracking-tight text-[clamp(2rem,4.5vw,3.25rem)] leading-[1.05] mb-5">{t("portfolio.title")}</h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">{t("portfolio.lead")}</p>
        </div>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {VIDEOS.map((item, index) => {
            const title = lang === "en" ? item.titleEn : item.titleEs;
            const desc = lang === "en" ? item.descEn : item.descEs;
            return (
              <a
                key={item.videoId}
                href={youtubeUrl(item.videoId)}
                target="_blank"
                rel="noopener noreferrer"
                className="block focus:outline-none focus:ring-2 focus:ring-primary rounded-lg"
                aria-label={`${t("portfolio.watch")} ${title}`}
                itemProp="itemListElement"
                itemScope
                itemType="https://schema.org/VideoObject"
              >
                <meta itemProp="position" content={String(index + 1)} />
                <meta itemProp="name" content={title} />
                <meta itemProp="description" content={desc} />
                <meta itemProp="uploadDate" content={item.uploadDate} />
                <meta itemProp="duration" content={item.durationISO} />
                <meta itemProp="contentUrl" content={youtubeUrl(item.videoId)} />
                <meta itemProp="embedUrl" content={youtubeEmbed(item.videoId)} />
                <link itemProp="thumbnailUrl" href={youtubeThumb(item.videoId)} />
                <Card
                  className={`group overflow-hidden cursor-pointer card-lift h-full rounded-2xl ${item.featured ? "border-primary/40 glow-violet" : ""}`}
                >
                  <CardContent className="p-0">
                    <div className="relative aspect-video overflow-hidden bg-muted">
                      <img
                        src={youtubeThumb(item.videoId)}
                        onLoad={(e) => handleImgLoad(e, item.videoId)}
                        onError={(e) => {
                          const img = e.currentTarget;
                          if (!img.src.includes("hqdefault")) img.src = youtubeThumbFallback(item.videoId);
                        }}
                        alt={title}
                        loading="lazy"
                        decoding="async"
                        width={1280}
                        height={720}
                        className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                      />
                      {item.featured && (
                        <div className="absolute top-3 left-3 z-10 bg-primary text-primary-foreground text-xs font-semibold px-3 py-1 rounded-full shadow-lg">
                          {t("portfolio.featured")}
                        </div>
                      )}
                      <div className="absolute top-3 right-3 z-10 bg-black/70 text-white text-xs font-semibold px-2 py-1 rounded">{item.durationLabel}</div>
                      <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent opacity-60 group-hover:opacity-80 transition-opacity duration-300" />
                      <div className="absolute inset-0 flex items-center justify-center">
                        <div className="bg-primary/90 rounded-full p-4 shadow-2xl group-hover:scale-110 transition-transform duration-300">
                          <Play className="h-8 w-8 text-primary-foreground fill-current" />
                        </div>
                      </div>
                    </div>
                    <div className="p-5">
                      <h3 className="font-bold text-lg text-foreground mb-2">{title}</h3>
                      <p className="text-sm text-muted-foreground leading-relaxed line-clamp-3">{desc}</p>
                    </div>
                  </CardContent>
                </Card>
              </a>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default Portfolio;
